/**
 * 从规范文档生成 spec/requirements.yaml（REQ-ENG-002）。每个唯一的 REQ-*
 * （core）和 REQ-APP-*（app）成为登记表的一行：id、摘录、所属 module、测试
 * 族、来源规范。规范中被引用的章节是规范来源；摘录会被截断。
 *
 * 溯源：本文件通过对已提交的规范运行本工具生成——绝不凭记忆撰写。
 * `pnpm reproduce` 会重跑它并在漂移时失败。
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

interface Req {
  id: string;
  excerpt: string;
  module: string;
  testFamily: string;
  spec: 'core' | 'app';
}

const ROOT = process.cwd();
const coreSpec = readFileSync(join(ROOT, 'spec/bsv-poker-spec.md'), 'utf8');
const appSpec = readFileSync(join(ROOT, 'spec/bsv-poker-app-architecture.md'), 'utf8');

/** 解析 core §19.F 登记表的行：| ID | excerpt | module(s) | test family |。 */
function parseCoreTable(md: string): Map<string, Req> {
  const reqs = new Map<string, Req>();
  for (const line of md.split('\n')) {
    const m = /^\|\s*(REQ-[A-Z]+-\d+)\s*\|(.+?)\|(.+?)\|(.+?)\|\s*$/.exec(line);
    if (!m) continue;
    const id = m[1]!;
    reqs.set(id, {
      id,
      excerpt: m[2]!.trim(),
      module: m[3]!.trim(),
      testFamily: m[4]!.trim(),
      spec: 'core',
    });
  }
  return reqs;
}

/** 收集文档中每个唯一的 REQ id（捕获任何不在表中的项）。 */
function allIds(md: string, prefix: RegExp): string[] {
  const set = new Set<string>();
  for (const m of md.matchAll(prefix)) set.add(m[0]);
  return [...set].sort((a, b) => {
    const fa = a.replace(/\d+$/, '');
    const fb = b.replace(/\d+$/, '');
    if (fa !== fb) return fa < fb ? -1 : 1;
    return Number(a.match(/\d+$/)![0]) - Number(b.match(/\d+$/)![0]);
  });
}

/** 为 app 的 REQ-APP-id 尽力提取摘录：定义它的行/段落上的文本。 */
function appExcerpt(md: string, id: string): string {
  // 查找 "(REQ-APP-NNN" 或 "REQ-APP-NNN " 后跟随的描述性文本
  const re = new RegExp(`${id}[):]?\\s+([^\\n]+)`);
  const m = re.exec(md);
  if (!m) return '(see app spec)';
  return m[1]!.replace(/\s+/g, ' ').slice(0, 140).trim();
}

function yamlEscape(s: string): string {
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

function main(): void {
  const core = parseCoreTable(coreSpec);
  // 确保每个 core id 都存在，即使它不在表中
  for (const id of allIds(coreSpec, /REQ-(?!APP)[A-Z]+-\d+/g)) {
    if (!core.has(id)) {
      core.set(id, { id, excerpt: '(see cited section)', module: '(tbd)', testFamily: '(tbd)', spec: 'core' });
    }
  }
  const appReqs: Req[] = allIds(appSpec, /REQ-APP-\d+/g).map((id) => ({
    id,
    excerpt: appExcerpt(appSpec, id),
    module: '(app layer — see §A18)',
    testFamily: '(see §A16)',
    spec: 'app',
  }));

  const all: Req[] = [...core.values(), ...appReqs];
  const lines: string[] = [
    '# Requirements register — generated by tools/extract-requirements.ts (REQ-ENG-002).',
    '# The cited spec section is canonical; excerpts are truncated. Do not edit by hand.',
    `# counts: core=${core.size} app=${appReqs.length} total=${all.length}`,
    'requirements:',
  ];
  for (const r of all) {
    lines.push(`  - id: ${r.id}`);
    lines.push(`    spec: ${r.spec}`);
    lines.push(`    excerpt: ${yamlEscape(r.excerpt)}`);
    lines.push(`    module: ${yamlEscape(r.module)}`);
    lines.push(`    testFamily: ${yamlEscape(r.testFamily)}`);
  }
  mkdirSync(join(ROOT, 'spec'), { recursive: true });
  const out = lines.join('\n') + '\n';
  writeFileSync(join(ROOT, 'spec/requirements.yaml'), out);
  console.log(`requirements.yaml written: core=${core.size} app=${appReqs.length} total=${all.length}`);
}

main();
