/**
 * 可追溯性映射（REQ-ENG-003）：Phase-0/1 构建所满足的每条需求都被映射到
 * 满足它的源文件和通过的测试。尚未实现的需求被有意省略，
 * 并报告为 "planned (later phase)" —— 一个如实的矩阵，从不声称
 * 已完整（P8）。PHASE01_REQUIRED 集合即门禁：每条都必须被追溯。
 */

export interface Trace {
  readonly files: readonly string[];
  readonly tests: readonly string[];
}

export const TRACE_MAP: Readonly<Record<string, Trace>> = {
  'REQ-ARCH-001': { files: ['packages/engine/src/fsm.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-ARCH-002': { files: ['packages/game-holdem/src/holdem.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-ARCH-003': { files: ['packages/game-holdem/src/holdem.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-POKER-001': { files: ['packages/protocol-types/src/cards.ts'], tests: ['packages/protocol-types/test/cards.test.ts'] },
  'REQ-POKER-002': { files: ['packages/protocol-types/src/serialize.ts'], tests: ['packages/protocol-types/test/serialize.test.ts'] },
  'REQ-POKER-003': { files: ['packages/hand-eval/src/high.ts', 'packages/hand-eval/src/low.ts'], tests: ['packages/hand-eval/test/vectors.test.ts'] },
  'REQ-POKER-004': { files: ['packages/hand-eval/src/high.ts'], tests: ['packages/hand-eval/test/vectors.test.ts'] },
  'REQ-POKER-005': { files: ['packages/hand-eval/src/high.ts'], tests: ['packages/hand-eval/test/vectors.test.ts'] },
  'REQ-POKER-006': { files: ['packages/hand-eval/src/low.ts'], tests: ['packages/hand-eval/test/vectors.test.ts'] },
  'REQ-FSM-007': { files: ['packages/hand-eval/src/low.ts'], tests: ['packages/hand-eval/test/vectors.test.ts'] },
  'REQ-POKER-007': { files: ['packages/hand-eval/src/high.ts'], tests: ['packages/hand-eval/test/vectors.test.ts'] },
  'REQ-POKER-008': { files: ['packages/engine/src/betting.ts'], tests: ['packages/engine/test/betting.test.ts'] },
  'REQ-POKER-009': { files: ['packages/engine/src/betting.ts'], tests: ['packages/engine/test/betting.test.ts'] },
  'REQ-POKER-010': { files: ['packages/engine/src/betting.ts'], tests: ['packages/engine/test/betting.test.ts'] },
  'REQ-POKER-011': { files: ['packages/engine/src/pots.ts'], tests: ['packages/engine/test/pots.test.ts'] },
  'REQ-POKER-012': { files: ['packages/engine/src/pots.ts'], tests: ['packages/engine/test/pots.test.ts'] },
  'REQ-POKER-013': { files: ['packages/engine/src/pots.ts'], tests: ['packages/engine/test/pots.test.ts'] },
  'REQ-FSM-001': { files: ['packages/engine/src/fsm.ts', 'packages/game-holdem/src/holdem.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-FSM-002': { files: ['packages/game-holdem/src/holdem.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-FSM-003': { files: ['packages/game-stud/src/stud.ts'], tests: ['packages/game-stud/test/stud.test.ts'] },
  'REQ-FSM-004': { files: ['packages/game-draw/src/draw.ts'], tests: ['packages/game-draw/test/draw.test.ts'] },
  'REQ-FSM-005': { files: ['packages/game-stud/src/stud.ts'], tests: ['packages/game-stud/test/stud.test.ts'] },
  'REQ-FSM-006': { files: ['packages/game-omaha/src/omaha.ts'], tests: ['packages/game-omaha/test/omaha.test.ts'] },
  'REQ-FSM-008': { files: ['packages/game-stud/src/stud.ts'], tests: ['packages/game-stud/test/stud.test.ts'] },
  'REQ-FSM-009': { files: ['packages/game-draw/src/draw.ts'], tests: ['packages/game-draw/test/draw.test.ts'] },
  'REQ-FSM-010': { files: ['packages/game-draw/src/draw.ts'], tests: ['packages/game-draw/test/draw.test.ts'] },
  'REQ-FSM-011': { files: ['packages/game-razz/src/razz.ts'], tests: ['packages/game-razz/test/razz.test.ts'] },
  'REQ-CRYPTO-001': { files: ['packages/crypto-mentalpoker/src/realct.ts'], tests: ['packages/crypto-mentalpoker/test/realct.test.ts'] },
  'REQ-CRYPTO-002': { files: ['packages/crypto-mentalpoker/src/realct.ts'], tests: ['packages/adapters/test/conformance.test.ts'] },
  'REQ-CRYPTO-003': { files: ['packages/crypto-mentalpoker/src/realct.ts'], tests: ['packages/crypto-mentalpoker/test/realct.test.ts'] },
  'REQ-CRYPTO-006': { files: ['packages/script-templates-ts/src/templates.ts'], tests: ['packages/script-templates-ts/test/templates.test.ts'] },
  'REQ-CRYPTO-009': { files: ['packages/script-templates-ts/src/templates.ts'], tests: ['packages/script-templates-ts/test/templates.test.ts'] },
  'REQ-WALLET-001': { files: ['packages/wallet-custody/src/custody.ts'], tests: ['packages/wallet-custody/test/custody.test.ts'] },
  'REQ-WALLET-002': { files: ['packages/wallet-custody/src/custody.ts'], tests: ['packages/wallet-custody/test/custody.test.ts'] },
  'REQ-WALLET-003': { files: ['packages/wallet-custody/src/custody.ts'], tests: ['packages/wallet-custody/test/custody.test.ts'] },
  'REQ-WALLET-004': { files: ['packages/wallet-custody/src/custody.ts'], tests: ['packages/wallet-custody/test/custody.test.ts'] },
  'REQ-WALLET-005': { files: ['packages/adapters/src/real-channel.ts', 'tools/microbet-e2e.ts'], tests: ['tools/microbet-e2e.ts'] },
  'REQ-PROD-001': { files: ['packages/wallet-custody/src/custody.ts', 'packages/app-services/src/wallet.ts'], tests: ['packages/app-services/test/wallet.test.ts'] },
  'REQ-POKER-016': { files: ['packages/sdk/src/table.ts'], tests: ['packages/sdk/test/table.test.ts'] },
  'REQ-TX-012': { files: ['packages/wallet-custody/src/custody.ts', 'packages/adapters/src/real-ob.ts'], tests: ['packages/wallet-custody/test/custody.test.ts', 'tools/mode-b-e2e.ts'] },
  'REQ-DEP-001': { files: ['packages/adapters/src/contracts.ts'], tests: ['packages/adapters/test/conformance.test.ts'] },
  'REQ-DEP-002': { files: ['packages/adapters/src/contracts.ts'], tests: ['packages/adapters/test/conformance.test.ts'] },
  'REQ-DEP-003': { files: ['packages/adapters/src/conformance.ts'], tests: ['packages/adapters/test/conformance.test.ts', 'packages/crypto-mentalpoker/test/realct.test.ts'] },
  'REQ-DEP-004': { files: ['packages/crypto-mentalpoker/src/realct.ts'], tests: ['packages/crypto-mentalpoker/test/realct.test.ts'] },
  'REQ-TX-001': { files: ['packages/script-templates-ts/src/interpreter.ts'], tests: ['packages/script-templates-ts/test/templates.test.ts'] },
  'REQ-TX-002': { files: ['packages/tx-builder/src/txbuilder.ts'], tests: ['packages/tx-builder/test/txbuilder.test.ts'] },
  'REQ-TX-004': { files: ['packages/script-templates-ts/src/opcodes.ts'], tests: ['packages/script-templates-ts/test/templates.test.ts'] },
  'REQ-TX-005': { files: ['packages/script-templates-ts/src/templates.ts'], tests: ['packages/tx-builder/test/txbuilder.test.ts'] },
  'REQ-TX-003': { files: ['packages/tx-builder/src/fallback.ts'], tests: ['packages/tx-builder/test/fallback.test.ts'] },
  'REQ-TX-006': { files: ['packages/tx-builder/src/fallback.ts', 'packages/engine/src/fsm.ts'], tests: ['packages/tx-builder/test/fallback.test.ts', 'packages/sdk/test/adversarial.test.ts'] },
  'REQ-TX-008': { files: ['packages/tx-builder/src/fallback.ts'], tests: ['packages/tx-builder/test/fallback.test.ts'] },
  'REQ-TX-010': { files: ['packages/script-templates-ts/src/templates.ts', 'tools/lint-opreturn.ts'], tests: ['packages/script-templates-ts/test/templates.test.ts'] },
  'REQ-TX-011': { files: ['packages/script-templates-ts/src/script.ts'], tests: ['packages/script-templates-ts/test/templates.test.ts'] },
  'REQ-NET-001': { files: ['apps/relay-go/relay/server.go'], tests: ['apps/relay-go/relay/relay_test.go'] },
  'REQ-NET-002': { files: ['packages/app-services/src/network.ts'], tests: ['packages/app-services/test/network.test.ts'] },
  'REQ-NET-003': { files: ['packages/app-services/src/network.ts'], tests: ['packages/app-services/test/network.test.ts'] },
  'REQ-NET-004': { files: ['apps/indexer-go/indexer/indexer.go'], tests: ['apps/indexer-go/indexer/indexer_test.go'] },
  'REQ-VM-002': { files: ['packages/adapters/src/real-node.ts', 'tools/node-e2e.ts'], tests: ['tools/node-e2e.ts'] },
  'REQ-NET-006': { files: ['apps/indexer-go/indexer/indexer.go'], tests: ['apps/indexer-go/indexer/indexer_test.go'] },
  'REQ-NET-007': { files: ['packages/app-services/src/transcript.ts', 'apps/indexer-go/indexer/indexer.go'], tests: ['apps/indexer-go/indexer/indexer_test.go'] },
  'REQ-PROD-011': { files: ['packages/app-services/src/transcript.ts'], tests: ['apps/indexer-go/indexer/indexer_test.go'] },
  'REQ-TEST-002': { files: ['packages/app-services/src/networked-table-client.ts', 'packages/game-holdem/src/holdem.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-DATA-002': { files: ['packages/protocol-types/src/tx.ts', 'packages/engine/src/fsm.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-DATA-003': { files: ['packages/game-holdem/src/holdem.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-DATA-004': { files: ['packages/adapters/src/fakes.ts'], tests: ['packages/adapters/test/seams.test.ts'] },
  'REQ-UI-001': { files: ['packages/app-services/src/local-table-client.ts'], tests: ['packages/app-services/test/local-table-client.test.ts'] },
  'REQ-UI-004': { files: ['packages/ui-core/src/view-models/table.ts'], tests: ['packages/ui-core/test/table-vm.test.ts'] },
  'REQ-UI-006': { files: ['packages/ui-core/src/view-models/signing.ts'], tests: ['packages/ui-core/test/showdown-signing-lobby-vm.test.ts'] },
  'REQ-APP-051': { files: ['packages/ui-core/src/view-models/table.ts'], tests: ['packages/ui-core/test/table-vm.test.ts'] },
  'REQ-APP-001': { files: ['packages/wallet-custody/src/custody.ts'], tests: ['packages/wallet-custody/test/custody.test.ts'] },
  'REQ-APP-002': { files: ['packages/app-services/src/network.ts'], tests: ['packages/app-services/test/network.test.ts'] },
  'REQ-APP-003': { files: ['packages/ui-core/src/view-models/table.ts'], tests: ['packages/ui-core/test/table-vm.test.ts'] },
  'REQ-APP-091': { files: ['packages/tx-builder/src/fallback.ts', 'packages/engine/src/fsm.ts'], tests: ['packages/sdk/test/adversarial.test.ts'] },
  'REQ-APP-093': { files: ['packages/ui-core/src/view-models/table-layout.ts', 'packages/game-holdem/src/holdem.ts'], tests: ['packages/ui-core/test/table-room-vm.test.ts'] },
  'REQ-APP-090': { files: ['packages/tx-builder/src/wire.ts', 'tools/perf-suite.ts'], tests: ['tools/perf-suite.ts'] },
  'REQ-APP-092': { files: ['packages/hand-eval/src/high.ts', 'tools/perf-suite.ts'], tests: ['tools/perf-suite.ts'] },
  'REQ-TEST-001': { files: ['packages/hand-eval/src/high.ts', 'packages/engine/src/pots.ts', 'packages/engine/src/betting.ts', 'packages/protocol-types/src/serialize.ts'], tests: ['packages/hand-eval/test/vectors.test.ts', 'packages/engine/test/pots.test.ts', 'packages/engine/test/betting.test.ts', 'packages/protocol-types/test/serialize.test.ts'] },
  'REQ-TEST-003': { files: ['packages/script-templates-ts/src/interpreter.ts'], tests: ['packages/script-templates-ts/test/templates.test.ts'] },
  'REQ-TEST-004': { files: ['packages/sdk/src/table.ts'], tests: ['packages/sdk/test/table.test.ts', 'packages/sdk/test/adversarial.test.ts'] },
  'REQ-PROD-006': { files: ['packages/ui-core/src/view-models/signing.ts'], tests: ['packages/ui-core/test/showdown-signing-lobby-vm.test.ts'] },
  'REQ-PROD-008': { files: ['packages/ui-core/src/view-models/showdown.ts'], tests: ['packages/ui-core/test/showdown-signing-lobby-vm.test.ts'] },
  'REQ-PROD-010': { files: ['packages/sdk/src/table.ts', 'packages/app-services/src/transcript.ts'], tests: ['packages/sdk/test/table.test.ts'] },
  'REQ-PROD-012': { files: ['packages/app-services/src/network-gate.ts'], tests: ['packages/app-services/test/network-gate.test.ts'] },
  'REQ-APP-012': { files: ['packages/adapters/src/index.ts', 'packages/adapters/src/contracts.ts'], tests: ['packages/adapters/test/architecture.test.ts'] },
  'REQ-APP-010': { files: ['packages/engine/src/fsm.ts', 'packages/sdk/src/table.ts'], tests: ['packages/sdk/test/table.test.ts'] },
  'REQ-APP-073': { files: ['packages/app-services/src/network.ts'], tests: ['packages/app-services/test/network.test.ts'] },
  'REQ-APP-075': { files: ['packages/app-services/src/interactive-client.ts'], tests: ['tools/reconnect-e2e.ts'] },
  'REQ-APP-081': { files: ['packages/wallet-custody/src/custody.ts'], tests: ['packages/wallet-custody/test/custody.test.ts'] },
  'REQ-APP-082': { files: ['packages/ui-core/src/view-models/signing.ts'], tests: ['packages/ui-core/test/showdown-signing-lobby-vm.test.ts'] },
  'REQ-APP-083': { files: ['packages/adapters/src/real-va.ts'], tests: ['packages/adapters/test/conformance.test.ts'] },
  'REQ-CRYPTO-008': { files: ['packages/wallet-custody/src/custody.ts'], tests: ['packages/wallet-custody/test/custody.test.ts'] },
  'REQ-CRYPTO-010': { files: ['packages/crypto-mentalpoker/src/realct.ts', 'packages/app-services/src/mp-shuffle.ts'], tests: ['packages/crypto-mentalpoker/test/realct.test.ts'] },
  'REQ-CRYPTO-012': { files: ['packages/tx-builder/src/fallback.ts'], tests: ['packages/sdk/test/adversarial.test.ts'] },
  'REQ-APP-050': { files: ['packages/ui-core/src/store/index.ts'], tests: ['packages/ui-core/test/store.test.ts'] },
  'REQ-APP-052': { files: ['packages/ui-core/src/view-models/lobby.ts', 'packages/ui-core/src/view-models/table.ts', 'packages/ui-core/src/view-models/wallet-panel.ts'], tests: ['packages/ui-core/test/lobby-vm.test.ts', 'packages/ui-core/test/table-vm.test.ts', 'packages/ui-core/test/table-room-vm.test.ts'] },
  'REQ-APP-053': { files: ['apps/client-web/src/screens/Connect.tsx'], tests: ['tests/web-interaction-rules.test.ts'] },
  'REQ-APP-042': { files: ['apps/client-web/src/App.tsx'], tests: ['tests/web-interaction-rules.test.ts'] },
  'REQ-UI-002': { files: ['apps/client-web/src/App.tsx'], tests: ['tests/web-interaction-rules.test.ts'] },
  'REQ-UI-003': { files: ['apps/client-web/src/screens/Connect.tsx'], tests: ['tests/web-interaction-rules.test.ts'] },
  'REQ-APP-045': { files: ['packages/app-services/src/interactive-client.ts'], tests: ['tools/reconnect-e2e.ts'] },
  'REQ-APP-070': { files: ['packages/app-services/src/network.ts', 'apps/relay-go/relay/server.go'], tests: ['apps/relay-go/relay/relay_test.go'] },
  'REQ-APP-071': { files: ['packages/app-services/src/lobby.ts', 'packages/app-services/src/network.ts'], tests: ['tools/lobby-e2e.ts'] },
  'REQ-APP-072': { files: ['packages/app-services/src/network.ts'], tests: ['packages/app-services/test/network.test.ts'] },
  'REQ-APP-029': { files: ['packages/app-services/src/network-gate.ts'], tests: ['packages/app-services/test/network-gate.test.ts'] },
  'REQ-APP-030': { files: ['packages/app-services/src/network-gate.ts'], tests: ['packages/app-services/test/network-gate.test.ts'] },
  'REQ-APP-101': { files: ['packages/wallet-custody/src/custody.ts'], tests: ['packages/wallet-custody/test/custody.test.ts'] },
  'REQ-APP-111': { files: ['packages/engine/src/fsm.ts'], tests: ['packages/sdk/test/adversarial.test.ts'] },
  'REQ-APP-112': { files: ['packages/app-services/src/network-gate.ts'], tests: ['packages/app-services/test/network-gate.test.ts'] },
  'REQ-APP-161': { files: ['packages/ui-core/src/view-models/table.ts'], tests: ['packages/ui-core/test/table-vm.test.ts'] },
  'REQ-APP-162': { files: ['packages/sdk/src/table.ts'], tests: ['packages/sdk/test/table.test.ts'] },
  'REQ-APP-181': { files: ['tools/trace-map.ts', 'tools/traceability.ts'], tests: ['tools/traceability.ts'] },
  'REQ-APP-210': { files: ['packages/game-holdem/src/holdem.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-APP-212': { files: ['packages/app-services/src/game-registry.ts'], tests: ['tools/multi-e2e.ts'] },
  'REQ-APP-214': { files: ['packages/ui-core/src/view-models/table.ts'], tests: ['packages/ui-core/test/table-vm.test.ts'] },
  'REQ-APP-241': { files: ['packages/adapters/src/real-channel.ts'], tests: ['tools/microbet-e2e.ts'] },
  'REQ-APP-242': { files: ['packages/adapters/src/real-channel.ts'], tests: ['tools/microbet-e2e.ts'] },
  'REQ-APP-120': { files: ['packages/app-services/src/observability.ts'], tests: ['packages/app-services/test/observability.test.ts'] },
  'REQ-APP-124': { files: ['packages/app-services/src/observability.ts'], tests: ['packages/app-services/test/observability.test.ts'] },
  'REQ-APP-121': { files: ['packages/app-services/src/observability.ts'], tests: ['packages/app-services/test/observability-metrics.test.ts'] },
  'REQ-APP-122': { files: ['packages/app-services/src/observability.ts'], tests: ['packages/app-services/test/observability-metrics.test.ts'] },
  'REQ-APP-131': { files: ['packages/app-services/src/persistence.ts'], tests: ['packages/app-services/test/persistence.test.ts'] },
  'REQ-APP-132': { files: ['packages/app-services/src/persistence.ts'], tests: ['packages/app-services/test/persistence.test.ts'] },
  'REQ-APP-103': { files: ['packages/app-services/src/message-validation.ts'], tests: ['packages/app-services/test/message-validation.test.ts'] },
  'REQ-APP-106': { files: ['packages/app-services/src/network-gate.ts'], tests: ['packages/app-services/test/network-gate.test.ts'] },
  'REQ-APP-054': { files: ['packages/ui-core/src/view-models/accessibility.ts'], tests: ['packages/ui-core/test/accessibility.test.ts'] },
  'REQ-ENG-001': { files: ['docs/adr/0003-self-contained-interpreter.md', 'docs/assurance.md', 'tools/perf-suite.ts'], tests: ['tools/perf-suite.ts'] },
  'REQ-ENG-004': { files: ['packages/app-services/src/network-gate.ts', 'packages/app-services/src/message-validation.ts'], tests: ['tests/boundaries.test.ts'] },
  'REQ-APP-160': { files: ['tools/ci.ts'], tests: ['packages/sdk/test/adversarial.test.ts'] },
  'REQ-APP-170': { files: ['docs/assurance.md', 'tools/traceability.ts'], tests: ['tools/traceability.ts'] },
  'REQ-APP-172': { files: ['docs/assurance.md', 'docs/redteam-02.md', 'packages/app-services/src/network-gate.ts'], tests: ['packages/app-services/test/network-gate.test.ts'] },
  'REQ-APP-180': { files: ['spec/requirements.yaml', 'tools/extract-requirements.ts'], tests: ['tools/traceability.ts'] },
  'REQ-APP-182': { files: ['tools/ci.ts', 'tools/traceability.ts'], tests: ['tools/traceability.ts'] },
  'REQ-VM-001': { files: ['tools/selftest.ts'], tests: ['tools/selftest.ts'] },
  'REQ-APP-020': { files: ['apps/client-desktop/src-tauri/src/main.rs'], tests: ['apps/client-desktop/src-tauri/src/main.rs'] },
  'REQ-APP-021': { files: ['apps/client-desktop/src-tauri/src/main.rs'], tests: ['apps/client-desktop/src-tauri/src/main.rs'] },
  'REQ-APP-022': { files: ['apps/client-desktop/src-tauri/src/main.rs'], tests: ['apps/client-desktop/src-tauri/src/main.rs'] },
  'REQ-APP-024': { files: ['apps/client-desktop/src-tauri/src/main.rs'], tests: ['apps/client-desktop/src-tauri/src/main.rs'] },
  'REQ-APP-026': { files: ['apps/client-desktop/src-tauri/src/main.rs'], tests: ['apps/client-desktop/src-tauri/src/main.rs'] },
  'REQ-APP-027': { files: ['apps/client-desktop/src-tauri/src/main.rs'], tests: ['apps/client-desktop/src-tauri/src/main.rs'] },
  'REQ-APP-028': { files: ['apps/client-desktop/src-tauri/src/main.rs'], tests: ['apps/client-desktop/src-tauri/src/main.rs'] },
  'REQ-CRYPTO-004': { files: ['packages/crypto-mentalpoker/src/realct.ts'], tests: ['packages/crypto-mentalpoker/test/realct.test.ts'] },
  'REQ-CRYPTO-007': { files: ['packages/script-templates-ts/src/templates.ts'], tests: ['packages/script-templates-ts/test/shuffle-key.test.ts'] },
  'REQ-VM-004': { files: ['apps/client-desktop/src-tauri/src/main.rs', 'apps/client-desktop/src-tauri/tauri.conf.json'], tests: ['apps/client-desktop/src-tauri/src/main.rs'] },
  'REQ-TEST-007': { files: ['tools/ci.ts', 'tools/traceability.ts'], tests: ['tools/traceability.ts'] },
  'REQ-CRYPTO-011': { files: ['packages/app-services/src/table-participants.ts', 'packages/app-services/src/interactive-client.ts'], tests: ['packages/app-services/test/table-participants.test.ts'] },
  'REQ-TX-007': { files: ['packages/tx-builder/src/timing.ts'], tests: ['packages/tx-builder/test/timing.test.ts'] },
  'REQ-APP-060': { files: ['packages/ui-core/src/view-models/signing.ts'], tests: ['packages/ui-core/test/showdown-signing-lobby-vm.test.ts'] },
  'REQ-APP-113': { files: ['packages/tx-builder/src/fallback.ts'], tests: ['packages/tx-builder/test/fallback.test.ts'] },
  'REQ-APP-114': { files: ['packages/tx-builder/src/fallback.ts', 'packages/engine/src/pots.ts'], tests: ['packages/tx-builder/test/fallback.test.ts'] },
  'REQ-APP-163': { files: ['packages/sdk/src/table.ts'], tests: ['packages/sdk/test/table.test.ts'] },
  'REQ-APP-164': { files: ['packages/script-templates-ts/src/interpreter.ts'], tests: ['packages/script-templates-ts/test/templates.test.ts'] },
  'REQ-APP-165': { files: ['packages/sdk/src/table.ts'], tests: ['packages/sdk/test/adversarial.test.ts'] },
  'REQ-APP-166': { files: ['tools/perf-suite.ts'], tests: ['tools/perf-suite.ts'] },
  'REQ-APP-167': { files: ['packages/ui-core/src/view-models/accessibility.ts'], tests: ['packages/ui-core/test/accessibility.test.ts'] },
  'REQ-APP-171': { files: ['docs/assurance.md', 'docs/adr/0003-self-contained-interpreter.md'], tests: ['tools/perf-suite.ts'] },
  'REQ-APP-211': { files: ['packages/ui-core/src/view-models/table.ts'], tests: ['packages/ui-core/test/table-vm.test.ts'] },
  'REQ-APP-213': { files: ['packages/app-services/src/game-registry.ts'], tests: ['tools/multi-e2e.ts'] },
  'REQ-APP-215': { files: ['packages/ui-core/src/view-models/table.ts'], tests: ['packages/ui-core/test/table-vm.test.ts'] },
  'REQ-APP-216': { files: ['packages/ui-core/src/view-models/bet-sizing.ts'], tests: ['packages/ui-core/test/table-room-vm.test.ts'] },
  'REQ-APP-217': { files: ['packages/ui-core/src/view-models/table-layout.ts'], tests: ['packages/ui-core/test/table-room-vm.test.ts'] },
  'REQ-APP-220': { files: ['packages/game-holdem/src/holdem.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-APP-219': { files: ['packages/app-services/src/game-registry.ts'], tests: ['packages/app-services/test/blackjack-reservation.test.ts'] },
  'REQ-APP-043': { files: ['packages/adapters/src/real-node.ts'], tests: ['tools/node-e2e.ts'] },
  'REQ-APP-080': { files: ['packages/ui-core/src/view-models/signing.ts'], tests: ['packages/ui-core/test/showdown-signing-lobby-vm.test.ts'] },
  'REQ-APP-094': { files: ['apps/client-desktop/src-tauri/tauri.conf.json', 'apps/client-desktop/src-tauri/src/main.rs'], tests: ['apps/client-desktop/src-tauri/src/main.rs'] },
  'REQ-APP-130': { files: ['packages/app-services/src/persistence.ts'], tests: ['packages/app-services/test/persistence.test.ts'] },
  'REQ-APP-140': { files: ['tools/perf-suite.ts'], tests: ['tools/perf-suite.ts'] },
  'REQ-APP-141': { files: ['tools/ci.ts'], tests: ['tools/traceability.ts'] },
  'REQ-APP-142': { files: ['tools/reproduce.ts'], tests: ['tools/reproduce.ts'] },
  'REQ-APP-218': { files: ['packages/app-services/src/game-registry.ts', 'packages/ui-core/src/view-models/table.ts'], tests: ['tools/multi-e2e.ts'] },
  'REQ-APP-221': { files: ['packages/app-services/src/game-registry.ts'], tests: ['tools/multi-e2e.ts'] },
  'REQ-APP-110': { files: ['packages/app-services/src/errors.ts'], tests: ['packages/app-services/test/errors-modes.test.ts'] },
  'REQ-APP-040': { files: ['packages/app-services/src/network-modes.ts'], tests: ['packages/app-services/test/errors-modes.test.ts'] },
  'REQ-APP-041': { files: ['packages/app-services/src/network-modes.ts'], tests: ['packages/app-services/test/errors-modes.test.ts'] },
  'REQ-APP-074': { files: ['packages/app-services/src/network-modes.ts'], tests: ['packages/app-services/test/errors-modes.test.ts'] },
  'REQ-APP-123': { files: ['packages/app-services/src/observability.ts'], tests: ['packages/app-services/test/observability-metrics.test.ts'] },
  'REQ-APP-150': { files: ['docs/runbook.md', 'docs/user-guide.md', 'docs/assurance.md'], tests: ['tests/docs-present.test.ts'] },
  'REQ-APP-151': { files: ['docs/adr/README.md'], tests: ['tests/docs-present.test.ts'] },
  'REQ-APP-173': { files: ['docs/assurance.md', 'docs/redteam-02.md'], tests: ['packages/app-services/test/network-gate.test.ts'] },
  'REQ-APP-183': { files: ['tools/ci.ts', 'spec/requirements.yaml'], tests: ['tools/traceability.ts'] },
  'REQ-APP-011': { files: ['packages/tx-builder/src/timing.ts'], tests: ['packages/tx-builder/test/timing.test.ts'] },
  'REQ-APP-023': { files: ['packages/app-services/src/network-modes.ts'], tests: ['packages/app-services/test/errors-modes.test.ts'] },
  'REQ-APP-100': { files: ['docs/redteam-02.md', 'packages/adapters/src/index.ts'], tests: ['packages/adapters/test/architecture.test.ts'] },
  'REQ-APP-102': { files: ['packages/wallet-custody/src/custody.ts'], tests: ['packages/wallet-custody/test/custody.test.ts'] },
  'REQ-APP-104': { files: ['docs/redteam-02.md', 'packages/app-services/src/network-gate.ts'], tests: ['packages/app-services/test/network-gate.test.ts'] },
  'REQ-APP-168': { files: ['packages/app-services/src/observability.ts', 'packages/app-services/src/network-gate.ts'], tests: ['packages/app-services/test/observability.test.ts'] },
  'REQ-APP-169': { files: ['tools/selftest.ts'], tests: ['tools/selftest.ts'] },
  'REQ-BUILD-002': { files: ['pnpm-lock.yaml', 'tools/reproduce.ts'], tests: ['tests/release-artifacts.test.ts'] },
  'REQ-VM-003': { files: ['apps/client-web/Dockerfile', 'vm/Dockerfile.node'], tests: ['tests/release-artifacts.test.ts'] },
  'REQ-APP-133': { files: ['packages/app-services/src/persistence.ts'], tests: ['packages/app-services/test/persistence.test.ts'] },
  'REQ-APP-025': { files: ['packages/wallet-custody/src/custody.ts'], tests: ['packages/wallet-custody/test/custody.test.ts'] },
  'REQ-APP-230': { files: ['packages/adapters/src/real-tee.ts'], tests: ['tools/tee-bind-e2e.ts'] },
  'REQ-APP-231': { files: ['packages/adapters/src/real-tee.ts'], tests: ['tools/tee-bind-e2e.ts'] },
  'REQ-APP-232': { files: ['packages/adapters/src/real-tee.ts'], tests: ['tools/tee-bind-e2e.ts'] },
  'REQ-APP-240': { files: ['packages/adapters/src/real-tee.ts'], tests: ['tools/tee-bind-e2e.ts'] },
  'REQ-NET-005': { files: ['packages/script-templates-ts/src/templates.ts'], tests: ['packages/sdk/test/adversarial.test.ts'] },
  'REQ-POKER-014': { files: ['packages/ui-core/src/view-models/showdown.ts'], tests: ['packages/ui-core/test/showdown-signing-lobby-vm.test.ts'] },
  'REQ-POKER-015': { files: ['packages/script-templates-ts/src/interpreter.ts'], tests: ['packages/sdk/test/adversarial.test.ts'] },
  'REQ-PROD-005': { files: ['packages/wallet-custody/src/custody.ts', 'packages/ui-core/src/view-models/showdown.ts'], tests: ['packages/wallet-custody/test/custody.test.ts'] },
  'REQ-UI-005': { files: ['packages/wallet-custody/src/custody.ts'], tests: ['packages/wallet-custody/test/custody.test.ts'] },
  'REQ-VM-007': { files: ['packages/app-services/src/network-gate.ts'], tests: ['packages/app-services/test/network-gate.test.ts'] },
  'REQ-PROD-002': { files: ['packages/ui-core/src/view-models/lobby.ts', 'packages/app-services/src/local-table-client.ts'], tests: ['packages/app-services/test/local-table-client.test.ts'] },
  'REQ-PROD-003': { files: ['packages/ui-core/src/view-models/lobby.ts'], tests: ['packages/ui-core/test/showdown-signing-lobby-vm.test.ts'] },
  'REQ-PROD-004': { files: ['packages/ui-core/src/view-models/table.ts'], tests: ['packages/ui-core/test/table-vm.test.ts'] },
  'REQ-PROD-007': { files: ['packages/game-holdem/src/holdem.ts', 'packages/ui-core/src/view-models/table.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-PROD-009': { files: ['packages/ui-core/src/view-models/showdown.ts'], tests: ['packages/ui-core/test/showdown-signing-lobby-vm.test.ts'] },
  'REQ-ENG-002': { files: ['tools/extract-requirements.ts'], tests: ['tools/reproduce.ts'] },
  'REQ-ENG-003': { files: ['tools/traceability.ts', 'tools/trace-map.ts'], tests: ['tools/traceability.ts'] },
  'REQ-TEST-005': { files: ['tools/reproduce.ts'], tests: ['tools/reproduce.ts'] },
  'REQ-TEST-006': { files: ['packages/sdk/test/adversarial.test.ts'], tests: ['packages/sdk/test/adversarial.test.ts'] },
  'REQ-CRYPTO-005': { files: ['packages/script-templates-ts/src/templates.ts'], tests: ['packages/sdk/test/adversarial.test.ts'] },
  'REQ-POKER-017': { files: ['packages/game-holdem/src/holdem.ts'], tests: ['packages/sdk/test/adversarial.test.ts'] },
  'REQ-BUILD-001': { files: ['pnpm-workspace.yaml'], tests: ['tools/ci.ts'] },
  'REQ-BUILD-003': { files: ['tools/ci.ts'], tests: ['tools/ci.ts'] },
};

/** Phase-0/1 门禁：这里的每个 id 都必须被追溯（REQ-TEST-007 / app §A18.3）。 */
export const PHASE01_REQUIRED: readonly string[] = Object.keys(TRACE_MAP);
