/**
 * Traceability map (REQ-ENG-003): every requirement the Phase-0/1 build SATISFIES is mapped to
 * its satisfying source file(s) and passing test(s). Requirements not yet implemented are
 * intentionally absent and reported as "planned (later phase)" — an honest matrix, never a
 * claim of completeness (P8). The PHASE01_REQUIRED set is the gate: each MUST be traced.
 */

export interface Trace {
  readonly files: readonly string[];
  readonly tests: readonly string[];
}

export const TRACE_MAP: Readonly<Record<string, Trace>> = {
  'REQ-ARCH-001': { files: ['packages/engine/src/fsm.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-ARCH-002': { files: ['packages/game-holdem/src/holdem.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-ARCH-003': { files: ['packages/game-holdem/src/holdem.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-POKER-001': { files: ['packages/protocol-types/src/cards.ts'], tests: ['packages/protocol-types/test/cards.test.ts'] },
  'REQ-POKER-002': { files: ['packages/protocol-types/src/serialize.ts'], tests: ['packages/protocol-types/test/serialize.test.ts'] },
  'REQ-POKER-003': { files: ['packages/hand-eval/src/high.ts', 'packages/hand-eval/src/low.ts'], tests: ['packages/hand-eval/test/vectors.test.ts'] },
  'REQ-POKER-004': { files: ['packages/hand-eval/src/high.ts'], tests: ['packages/hand-eval/test/vectors.test.ts'] },
  'REQ-POKER-005': { files: ['packages/hand-eval/src/high.ts'], tests: ['packages/hand-eval/test/vectors.test.ts'] },
  'REQ-POKER-006': { files: ['packages/hand-eval/src/low.ts'], tests: ['packages/hand-eval/test/vectors.test.ts'] },
  'REQ-FSM-007': { files: ['packages/hand-eval/src/low.ts'], tests: ['packages/hand-eval/test/vectors.test.ts'] },
  'REQ-POKER-007': { files: ['packages/hand-eval/src/high.ts'], tests: ['packages/hand-eval/test/vectors.test.ts'] },
  'REQ-POKER-008': { files: ['packages/engine/src/betting.ts'], tests: ['packages/engine/test/betting.test.ts'] },
  'REQ-POKER-009': { files: ['packages/engine/src/betting.ts'], tests: ['packages/engine/test/betting.test.ts'] },
  'REQ-POKER-010': { files: ['packages/engine/src/betting.ts'], tests: ['packages/engine/test/betting.test.ts'] },
  'REQ-POKER-011': { files: ['packages/engine/src/pots.ts'], tests: ['packages/engine/test/pots.test.ts'] },
  'REQ-POKER-012': { files: ['packages/engine/src/pots.ts'], tests: ['packages/engine/test/pots.test.ts'] },
  'REQ-POKER-013': { files: ['packages/engine/src/pots.ts'], tests: ['packages/engine/test/pots.test.ts'] },
  'REQ-FSM-001': { files: ['packages/engine/src/fsm.ts', 'packages/game-holdem/src/holdem.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-FSM-002': { files: ['packages/game-holdem/src/holdem.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-FSM-003': { files: ['packages/game-stud/src/stud.ts'], tests: ['packages/game-stud/test/stud.test.ts'] },
  'REQ-FSM-004': { files: ['packages/game-draw/src/draw.ts'], tests: ['packages/game-draw/test/draw.test.ts'] },
  'REQ-FSM-005': { files: ['packages/game-stud/src/stud.ts'], tests: ['packages/game-stud/test/stud.test.ts'] },
  'REQ-FSM-006': { files: ['packages/game-omaha/src/omaha.ts'], tests: ['packages/game-omaha/test/omaha.test.ts'] },
  'REQ-FSM-008': { files: ['packages/game-stud/src/stud.ts'], tests: ['packages/game-stud/test/stud.test.ts'] },
  'REQ-FSM-009': { files: ['packages/game-draw/src/draw.ts'], tests: ['packages/game-draw/test/draw.test.ts'] },
  'REQ-FSM-010': { files: ['packages/game-draw/src/draw.ts'], tests: ['packages/game-draw/test/draw.test.ts'] },
  'REQ-FSM-011': { files: ['packages/game-razz/src/razz.ts'], tests: ['packages/game-razz/test/razz.test.ts'] },
  'REQ-CRYPTO-001': { files: ['packages/crypto-mentalpoker/src/realct.ts'], tests: ['packages/crypto-mentalpoker/test/realct.test.ts'] },
  'REQ-CRYPTO-002': { files: ['packages/crypto-mentalpoker/src/realct.ts'], tests: ['packages/adapters/test/conformance.test.ts'] },
  'REQ-CRYPTO-003': { files: ['packages/crypto-mentalpoker/src/realct.ts'], tests: ['packages/crypto-mentalpoker/test/realct.test.ts'] },
  'REQ-CRYPTO-006': { files: ['packages/script-templates-ts/src/templates.ts'], tests: ['packages/script-templates-ts/test/templates.test.ts'] },
  'REQ-CRYPTO-009': { files: ['packages/script-templates-ts/src/templates.ts'], tests: ['packages/script-templates-ts/test/templates.test.ts'] },
  'REQ-WALLET-001': { files: ['packages/wallet-custody/src/custody.ts'], tests: ['packages/wallet-custody/test/custody.test.ts'] },
  'REQ-WALLET-002': { files: ['packages/wallet-custody/src/custody.ts'], tests: ['packages/wallet-custody/test/custody.test.ts'] },
  'REQ-WALLET-003': { files: ['packages/wallet-custody/src/custody.ts'], tests: ['packages/wallet-custody/test/custody.test.ts'] },
  'REQ-WALLET-004': { files: ['packages/wallet-custody/src/custody.ts'], tests: ['packages/wallet-custody/test/custody.test.ts'] },
  'REQ-POKER-016': { files: ['packages/sdk/src/table.ts'], tests: ['packages/sdk/test/table.test.ts'] },
  'REQ-TX-012': { files: ['packages/wallet-custody/src/custody.ts'], tests: ['packages/wallet-custody/test/custody.test.ts'] },
  'REQ-DEP-001': { files: ['packages/adapters/src/contracts.ts'], tests: ['packages/adapters/test/conformance.test.ts'] },
  'REQ-DEP-002': { files: ['packages/adapters/src/contracts.ts'], tests: ['packages/adapters/test/conformance.test.ts'] },
  'REQ-DEP-003': { files: ['packages/adapters/src/conformance.ts'], tests: ['packages/adapters/test/conformance.test.ts', 'packages/crypto-mentalpoker/test/realct.test.ts'] },
  'REQ-DEP-004': { files: ['packages/crypto-mentalpoker/src/realct.ts'], tests: ['packages/crypto-mentalpoker/test/realct.test.ts'] },
  'REQ-TX-001': { files: ['packages/script-templates-ts/src/interpreter.ts'], tests: ['packages/script-templates-ts/test/templates.test.ts'] },
  'REQ-TX-002': { files: ['packages/tx-builder/src/txbuilder.ts'], tests: ['packages/tx-builder/test/txbuilder.test.ts'] },
  'REQ-TX-004': { files: ['packages/script-templates-ts/src/opcodes.ts'], tests: ['packages/script-templates-ts/test/templates.test.ts'] },
  'REQ-TX-005': { files: ['packages/script-templates-ts/src/templates.ts'], tests: ['packages/tx-builder/test/txbuilder.test.ts'] },
  'REQ-TX-010': { files: ['packages/script-templates-ts/src/templates.ts', 'tools/lint-opreturn.ts'], tests: ['packages/script-templates-ts/test/templates.test.ts'] },
  'REQ-TX-011': { files: ['packages/script-templates-ts/src/script.ts'], tests: ['packages/script-templates-ts/test/templates.test.ts'] },
  'REQ-NET-001': { files: ['apps/relay-go/relay/server.go'], tests: ['apps/relay-go/relay/relay_test.go'] },
  'REQ-NET-002': { files: ['packages/app-services/src/network.ts'], tests: ['packages/app-services/test/network.test.ts'] },
  'REQ-NET-003': { files: ['packages/app-services/src/network.ts'], tests: ['packages/app-services/test/network.test.ts'] },
  'REQ-NET-004': { files: ['apps/indexer-go/indexer/indexer.go'], tests: ['apps/indexer-go/indexer/indexer_test.go'] },
  'REQ-VM-002': { files: ['packages/adapters/src/real-node.ts', 'tools/node-e2e.ts'], tests: ['tools/node-e2e.ts'] },
  'REQ-NET-006': { files: ['apps/indexer-go/indexer/indexer.go'], tests: ['apps/indexer-go/indexer/indexer_test.go'] },
  'REQ-NET-007': { files: ['packages/app-services/src/networked-table-client.ts'], tests: ['apps/indexer-go/indexer/indexer_test.go'] },
  'REQ-TEST-002': { files: ['packages/app-services/src/networked-table-client.ts', 'packages/game-holdem/src/holdem.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-DATA-002': { files: ['packages/protocol-types/src/tx.ts', 'packages/engine/src/fsm.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-DATA-003': { files: ['packages/game-holdem/src/holdem.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-DATA-004': { files: ['packages/adapters/src/fakes.ts'], tests: ['packages/adapters/test/seams.test.ts'] },
  'REQ-UI-001': { files: ['packages/app-services/src/local-table-client.ts'], tests: ['packages/app-services/test/local-table-client.test.ts'] },
  'REQ-UI-004': { files: ['packages/ui-core/src/view-models/table.ts'], tests: ['packages/ui-core/test/table-vm.test.ts'] },
  'REQ-UI-006': { files: ['packages/ui-core/src/view-models/signing.ts'], tests: ['packages/ui-core/test/showdown-signing-lobby-vm.test.ts'] },
  'REQ-APP-051': { files: ['packages/ui-core/src/view-models/table.ts'], tests: ['packages/ui-core/test/table-vm.test.ts'] },
  'REQ-PROD-002': { files: ['packages/ui-core/src/view-models/lobby.ts', 'packages/app-services/src/local-table-client.ts'], tests: ['packages/app-services/test/local-table-client.test.ts'] },
  'REQ-PROD-003': { files: ['packages/ui-core/src/view-models/lobby.ts'], tests: ['packages/ui-core/test/showdown-signing-lobby-vm.test.ts'] },
  'REQ-PROD-004': { files: ['packages/ui-core/src/view-models/table.ts'], tests: ['packages/ui-core/test/table-vm.test.ts'] },
  'REQ-PROD-007': { files: ['packages/game-holdem/src/holdem.ts', 'packages/ui-core/src/view-models/table.ts'], tests: ['packages/game-holdem/test/holdem.test.ts'] },
  'REQ-PROD-009': { files: ['packages/ui-core/src/view-models/showdown.ts'], tests: ['packages/ui-core/test/showdown-signing-lobby-vm.test.ts'] },
  'REQ-ENG-002': { files: ['tools/extract-requirements.ts'], tests: ['tools/reproduce.ts'] },
  'REQ-ENG-003': { files: ['tools/traceability.ts', 'tools/trace-map.ts'], tests: ['tools/traceability.ts'] },
  'REQ-TEST-005': { files: ['tools/reproduce.ts'], tests: ['tools/reproduce.ts'] },
  'REQ-TEST-006': { files: ['packages/sdk/test/adversarial.test.ts'], tests: ['packages/sdk/test/adversarial.test.ts'] },
  'REQ-CRYPTO-005': { files: ['packages/script-templates-ts/src/templates.ts'], tests: ['packages/sdk/test/adversarial.test.ts'] },
  'REQ-POKER-017': { files: ['packages/game-holdem/src/holdem.ts'], tests: ['packages/sdk/test/adversarial.test.ts'] },
  'REQ-BUILD-001': { files: ['pnpm-workspace.yaml'], tests: ['tools/ci.ts'] },
  'REQ-BUILD-003': { files: ['tools/ci.ts'], tests: ['tools/ci.ts'] },
};

/** The Phase-0/1 gate: every id here MUST be traced (REQ-TEST-007 / app §A18.3). */
export const PHASE01_REQUIRED: readonly string[] = Object.keys(TRACE_MAP);
