/**
 * 可追溯性矩阵检查器（REQ-ENG-003, core §13.3）。将每条需求 → 代码 → 测试 进行映射，
 * 如果任何 PHASE01_REQUIRED 需求缺少满足它的测试，或某条追溯指向缺失的文件，
 * 则使构建失败。如实报告覆盖率；从不声称已完整（P8）。
 *
 * 完整完成的强制要求（223 条需求全部被追溯）是后续阶段的门禁；
 * 本阶段仅对构建声称满足的需求设门禁。
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { TRACE_MAP, PHASE01_REQUIRED } from './trace-map.ts';

const ROOT = process.cwd();

function loadRequirementIds(): string[] {
  const yaml = readFileSync(join(ROOT, 'spec/requirements.yaml'), 'utf8');
  const ids: string[] = [];
  for (const line of yaml.split('\n')) {
    const m = /^\s*-\s*id:\s*(REQ-[A-Z]+-\d+)\s*$/.exec(line);
    if (m) ids.push(m[1]!);
  }
  return ids;
}

function main(): void {
  const ids = loadRequirementIds();
  if (ids.length === 0) {
    console.error('traceability: requirements.yaml not found or empty — run extract-requirements first');
    process.exit(1);
  }
  const idSet = new Set(ids);
  const failures: string[] = [];

  // 每个被追溯的 id 都必须存在于登记表中，且其文件/测试必须存在于磁盘上。
  for (const [id, trace] of Object.entries(TRACE_MAP)) {
    if (!idSet.has(id)) failures.push(`${id}: traced but not in requirements.yaml`);
    for (const f of [...trace.files, ...trace.tests]) {
      if (!existsSync(join(ROOT, f))) failures.push(`${id}: missing file ${f}`);
    }
    if (trace.tests.length === 0) failures.push(`${id}: no satisfying test`);
  }

  // 门禁：每条 PHASE01_REQUIRED 需求都必须被追溯到至少一个测试。
  for (const id of PHASE01_REQUIRED) {
    const t = TRACE_MAP[id];
    if (!t || t.tests.length === 0) failures.push(`PHASE01 gate: ${id} is not traced to a test`);
  }

  const traced = Object.keys(TRACE_MAP).length;
  const coverage = ((traced / ids.length) * 100).toFixed(1);

  // 产出矩阵产物。
  const matrix: string[] = ['# Traceability matrix — generated by tools/traceability.ts (REQ-ENG-003).', ''];
  for (const id of ids) {
    const t = TRACE_MAP[id];
    matrix.push(`${id}: ${t ? `traced -> [${t.files.join(', ')}] tests [${t.tests.join(', ')}]` : 'planned (later phase)'}`);
  }
  writeFileSync(join(ROOT, 'spec/traceability.txt'), matrix.join('\n') + '\n');

  console.log(`Requirements: ${ids.length} total; ${traced} traced (${coverage}%); ${ids.length - traced} planned.`);
  if (failures.length > 0) {
    console.error('TRACEABILITY FAILED:');
    for (const f of failures) console.error('  - ' + f);
    process.exit(1);
  }
  console.log(`Traceability OK — all ${PHASE01_REQUIRED.length} Phase-0/1 requirements trace to passing tests.`);
}

main();
